---
- name: Install packages
  ansible.builtin.package:
    name: "{{ system_setup_packages }}"
    state: latest

- name: Set same timezone on every Server
  community.general.timezone:
    name: "{{ system_setup_timezone }}"

- name: Set SELinux to disabled state
  ansible.posix.selinux:
    state: disabled
  when: ansible_os_family == "RedHat"

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: yes

- name: Enable IPv6 router advertisements
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_ra
    value: "2"
    state: present
    reload: yes

- name: Enable syn flood protection
  ansible.posix.sysctl:
    name: net.ipv4.tcp_syncookies
    value: "1"
    state: present
    reload: yes

- name: Enable reverse path filtering
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.rp_filter
    value: "1"
    state: present
    reload: yes

- name: Enable reverse path filtering
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.rp_filter
    value: "1"
    state: present
    reload: yes

- name: Ignore source-routed packets
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.accept_source_route
    value: "0"
    state: present
    reload: yes

- name: Ignore source-routed packets
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.accept_source_route
    value: "0"
    state: present
    reload: yes

- name: Ignore source-routed packets
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_source_route
    value: "0"
    state: present
    reload: yes

- name: Ignore source-routed packets
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_source_route
    value: "0"
    state: present
    reload: yes

- name: Ignore ICMP redirects
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.accept_redirects
    value: "0"
    state: present
    reload: yes

- name: Ignore ICMP redirects
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.accept_redirects
    value: "0"
    state: present
    reload: yes

- name: Disable ICMP redirects
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.send_redirects
    value: "0"
    state: present
    reload: yes

- name: Disable ICMP redirects
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.send_redirects
    value: "0"
    state: present
    reload: yes

- name: Ignore ICMP redirects
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_redirects
    value: "0"
    state: present
    reload: yes

- name: Ignore ICMP redirects
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.accept_redirects
    value: "0"
    state: present
    reload: yes

- name: Ignore ICMP redirects from non-GW hosts
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.secure_redirects
    value: "1"
    state: present
    reload: yes

- name: Ignore ICMP redirects from non-GW hosts
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.secure_redirects
    value: "1"
    state: present
    reload: yes

- name: Ignore ICMP broadcasts to avoid participating in Smurf attacks
  ansible.posix.sysctl:
    name: net.ipv4.icmp_echo_ignore_broadcasts
    value: "1"
    state: present
    reload: yes

- name: Ignore bad ICMP errors
  ansible.posix.sysctl:
    name: net.ipv4.icmp_ignore_bogus_error_responses
    value: "1"
    state: present
    reload: yes

- name: Enable RFC 1337 fix
  ansible.posix.sysctl:
    name: net.ipv4.tcp_rfc1337
    value: "1"
    state: present
    reload: yes

- name: Log spoofed, source-routed, and redirect packets
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.log_martians
    value: "1"
    state: present
    reload: yes

- name: Log spoofed, source-routed, and redirect packets
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.log_martians
    value: "1"
    state: present
    reload: yes

- name: Randomize addresses of mmap base, heap, stack and VDSO page
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: "2"
    state: present
    reload: yes

- name: Randomize addresses of mmap base, heap, stack and VDSO page
  ansible.posix.sysctl:
    name: kernel.randomize_va_space
    value: "2"
    state: present
    reload: yes

- name: Provide protection from ToCToU races
  ansible.posix.sysctl:
    name: fs.protected_hardlinks
    value: "1"
    state: present
    reload: yes
  ignore_errors: true

- name: Provide protection from ToCToU races
  ansible.posix.sysctl:
    name: fs.protected_symlinks
    value: "1"
    state: present
    reload: yes
  ignore_errors: true

- name: Disable Proxy ARP
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.proxy_arp
    value: "0"
    state: present
    reload: yes

- name: Disable Proxy ARP
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.proxy_arp
    value: "0"
    state: present
    reload: yes

- name: Disable ARP Filter
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.arp_filter
    value: "0"
    state: present
    reload: yes

- name: Disable ARP Filter
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_filter
    value: "0"
    state: present
    reload: yes

- name: Disable ipv6 autoconf
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.autoconf
    value: "0"
    state: present
    reload: yes

- name: Disable ipv6 autoconf
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.autoconf
    value: "0"
    state: present
    reload: yes
  ignore_errors: true

- name: Set ARP Ignore to 2
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.arp_ignore
    value: "2"
    state: present
    reload: yes
  ignore_errors: true

- name: Set ARP Ignore to 2
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_ignore
    value: "2"
    state: present
    reload: yes
  ignore_errors: true

- name: Set ARP Announce to 1
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.arp_announce
    value: "1"
    state: present
    reload: yes
  ignore_errors: true

- name: Set ARP Announce to 1
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_announce
    value: "1"
    state: present
    reload: yes
  ignore_errors: true

- name: Disable ARP Notify
  ansible.posix.sysctl:
    name: net.ipv4.conf.default.arp_notify
    value: "0"
    state: present
    reload: yes
  ignore_errors: true

- name: Disable ARP Notify
  ansible.posix.sysctl:
    name: net.ipv4.conf.all.arp_notify
    value: "0"
    state: present
    reload: yes
  ignore_errors: true

- name: Ignore Router Advertisements
  ansible.posix.sysctl:
    name: net.ipv6.conf.default.accept_ra
    value: "0"
    state: present
    reload: yes
  ignore_errors: true

# - name: Ignore Router Advertisements
#   ansible.posix.sysctl:
#     name: net.ipv6.conf.all.accept_ra
#     value: "0"
#     state: present
#     reload: yes

- name: Set IPv6 route max size
  ansible.posix.sysctl:
    name: net.ipv6.route.max_size
    value: "262144"
    state: present
    reload: yes

- name: Add br_netfilter to /etc/modules-load.d/
  ansible.builtin.copy:
    content: "br_netfilter"
    dest: /etc/modules-load.d/br_netfilter.conf
    mode: "u=rw,g=,o="
  when: ansible_os_family == "RedHat"

- name: Load br_netfilter
  community.general.modprobe:
    name: br_netfilter
    state: present
  when: ansible_os_family == "RedHat"

- name: Set bridge-nf-call-iptables (just to be sure)
  ansible.posix.sysctl:
    name: "{{ item }}"
    value: "1"
    state: present
    reload: yes
  when: ansible_os_family == "RedHat"
  loop:
    - net.bridge.bridge-nf-call-iptables
    - net.bridge.bridge-nf-call-ip6tables

- name: Add /usr/local/bin to sudo secure_path
  ansible.builtin.lineinfile:
    line: 'Defaults    secure_path = /sbin:/bin:/usr/sbin:/usr/bin:/usr/local/bin'
    regexp: "Defaults(\\s)*secure_path(\\s)*="
    state: present
    insertafter: EOF
    path: /etc/sudoers
    validate: 'visudo -cf %s'
  when: ansible_os_family == "RedHat"

- name: Set hostname
  ansible.builtin.hostname:
   name: "{{ system_setup_hostname }}"

- name: Update grub
  ansible.builtin.lineinfile: 
    path: /etc/default/grub
    regexp: "^GRUB_CMDLINE_LINUX"
    line: 'GRUB_CMDLINE_LINUX="net.ifnames=0 biosdevname=0"'
    state: present
  notify: make grub config
  ignore_errors: true

- name: Clear ram cache
  ansible.builtin.cron:
    name: "clean ram cache"
    special_time: hourly
    job: "sync; echo 3 > /proc/sys/vm/drop_caches"
